# https://lightning.ai/docs/pytorch/stable/api_references.html#callbacks
# this argument can be used to add a Callback or a list of them for trainer
# callbacks run sequentially in the order defined here except ModelCheckpoint callbacks
# which run after all others to ensure all states are saved to the checkpoints

defaults:
  - device_stats_monitor
  - early_stopping
  - model_checkpoint
  - rich_model_summary
  - rich_progress_bar
  - _self_

ModelCheckpoint:
  dirpath: ${paths.output_dir}/checkpoints
  filename: checkpoints_{epoch:03d}
  monitor: train_acc
  mode: max
  save_top_k: 2
  every_n_epochs: 1
  auto_insert_metric_name: false
  enable_version_counter: true

EarlyStopping:
  monitor: val_acc
  patience: 100
  mode: max

RichModelSummary:
  max_depth: -1
