# https://lightning.ai/docs/pytorch/latest/api/lightning.pytorch.callbacks.RichProgressBar.html

RichProgressBar:
  _target_: lightning.pytorch.callbacks.RichProgressBar
  refresh_rate: 1
  leave: true
